---
title: "digital_twins_script"
output: html_document
date: "2023-07-07"
---

```{r}
library(ensembldb)
library(STRINGdb)
library(igraph)
library(UniProt.ws)
library(readxl)
library(dplyr)
library(tidyverse)
library(magrittr)
library(biomaRt)
# sup <- UniProt.ws(UniProt.version = "uniprot", use.cache = TRUE)
# BiocManager::install("STRINGdb")
string_db <- STRINGdb$new( version="11.5", species=9606, score_threshold=400, network_type="full", input_directory="/Users/niels/Documents/Uni/Stage/digital_twins/") # Save locally to save reconnecting to STRINGdb
```


```{r}
# Read siginificant cluster proteins
clust_proteins <- read.csv("/Users/niels/Documents/Uni/Stage/digital_twins/cluster_proteins.csv")
clust_proteins <- clust_proteins[, 1]

# Read and format fold change data accross disease stages
fold_data <- readxl::read_xlsx("/Users/niels/Documents/Uni/Stage/digital_twins/fold_data.xlsx") %>%
  as.data.frame() %>%
  dplyr::select(c(-1, )) %>%
  dplyr::filter(!row_number() %in% c(247, 248, 249)) %>%
  column_to_rownames(var = "Gene name") %>%
  separate(col = "late_vs_ctrl_95%CI", sep = "-", into = c("late_vs_ctrl_95%CI_low", "late_vs_ctrl_95%CI_high")) %>%
  separate(col = "early_vs_ctrl_95%CI", sep = "-", into = c("early_vs_ctrl_95%CI_low", "early_vs_ctrl_95%CI_high")) %>%
  separate(col = "late_vs_early_95%CI", sep = "-", into = c("late_vs_early_95%CI_low", "late_vs_early_95%CI_high")) %>%
  mutate(across(2:8, ~ as.numeric(gsub(",", ".", .)))) %>%
  mutate(across(2:8, log2))

# Create sig which will contain genes with significantly changed proteins expressions and sig_fold with the fold change
sig <- c()
sig_fold <- list()
i <- 0

# Filling sig and sig fold with names and values respectively
for (i in 1:length(rownames(fold_data))) {
  early <- fold_data$early_vs_ctrl_mean[i]
  late <- fold_data$late_vs_ctrl_mean[i]
  protein <- c(fold_data$`Protein AC`)[i]
  i <- i + 1
  if (early >= 1.8 || early <= -1.8) { # Why is the threshold 1.8 when the article clearly states 2?
    sig <- c(sig, protein)
    sig_fold <- c(sig_fold, early)
  } else if (late >= 1.8 || late <= -1.8) {
    sig <- c(sig, protein)
    sig_fold <- c(sig_fold, late)
  }
}

# Naming the list of sig_fold
names(sig_fold) <- sig
```

#### Reading data and determining mean and std

```{r}
# Read in data and calculating mean and standard deviation values for each gene
data <- readRDS("/Users/niels/Documents/Uni/Stage/digital_twins/X1_dig_twin_data.rds")
mean_values <- colMeans(data)
std_values <- apply(data, 2, sd)

# Creating vector data_proteins of all genes/proteins in our original dataset
data_proteins <- colnames(data)
```

#### Ensembl

```{r}
cluster_ensembl <- c()
proteins_ensembl <- c()

# Creating vector by mapping cluster uniprot characters to ensembl using STRING
for (i in seq_along(clust_proteins)) {
  string_map <- string_db$mp(clust_proteins[i])
  cluster_ensembl <- c(cluster_ensembl, string_map)
}

# Creating vector by mapping all original data uniprot proteins to ensembl using STRING
for (i in seq_along(data_proteins)) {
  string_map <- string_db$mp(clust_proteins[i])
  proteins_ensembl <- c(proteins_ensembl, string_map)
}

# Creating a list by mapping our significant fold proteins to their neighbours and keeping the proteins in our dataset
neightbours_list <- lapply(seq_along(sig), function(i) {
  string_map <- string_db$mp(sig[i])
  neighbours <- string_db$get_neighbors(string_map)
  intersect_neighbours <- intersect(c(string_map, neighbours), proteins_ensembl)
  return(intersect_neighbours)
})

# Naming neightbours_list
names(neightbours_list) <- sig

# Creating a list of all unique cluster proteins in the neightbours_list and their neighbours
cluster_list <- lapply(unique(unlist(neightbours_list)), function(clust_id) {
  outp <- sapply(seq_along(neightbours_list), function(clust_ii) {
    if (clust_id %in% neightbours_list[[clust_ii]]) {
      return(sig[clust_ii])
    } else {
      NA
    }
  })
  return(c(na.omit(outp)))   # Removing NA values from the list
})

# Naming cluster_list
names(cluster_list) <- unique(unlist(neightbours_list))
```

#### Unitprot function

```{r}
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# Function to convert Ensembl characters to uniprot
convert_ensembl_to_uniprot <- function(ensembl_ids) {
  if (length(ensembl_ids) == 0) {
    return(character())
  }
  ensembl_ids <- gsub("9606\\.", "", ensembl_ids)    # STRING mapping returns values starting with 9606. which is first removed
  result <- tryCatch(
    {
      getBM(
        attributes = c("ensembl_peptide_id", "uniprotswissprot"),
        filters = "ensembl_peptide_id",
        values = ensembl_ids,
        mart = ensembl
      )
    },
    error = function(e) {
      return(character())
    }
  )
  if (inherits(result, "try-error")) {
    return(character())
  }
  return(result$uniprotswissprot)
}
```

#### Uniprot ID's

```{r}
betas_list <- list()

# Filling betas list with mapping proteins and scoring their interactions
for (i in seq_along(cluster_list)) {
  str_names <- c(names(cluster_list)[i], cluster_list[[i]])
  string_map <- string_db$mp(str_names)
  str_intr <- string_db$get_subnetwork(string_map)
  E(str_intr)$combined_score %<>% divide_by(2000)   # Scoring function {insert source}
  str_nw <- as_adj(str_intr, attr = "combined_score")
  betas <- str_nw[string_map[-1], string_map[1]]
  if (length(betas) == 1) {
    protein <- names(cluster_list[i])
    protein_ensembl <- cluster_list[[paste0("", protein, "")]]
    betas <- setNames(betas, protein_ensembl)
  }
  # print(betas)
  betas_list[[i]] <- betas
  if (length(betas) > 1) {
    names(betas_list[[i]]) <- sapply(names(betas_list[[i]]), convert_ensembl_to_uniprot)
  }
}

# Naming the entries in the betas list by converting convert_ensembl_to_uniprot
names(betas_list) <- sapply(names(cluster_list), convert_ensembl_to_uniprot)

# Some Ensembl ID's are now in the uniprot archive. Manual search gives these corresponding uniprot ID's
names(betas_list)[3] <- "P01042"
names(betas_list)[36] <- "P61769"
names(betas_list)[39] <- "P02746"

# Removing 1 duplicate from list
if (any(duplicated(names(betas_list)))) betas_list <- betas_list[-which(duplicated(names(betas_list)))]
```

#### Saving/reading variables

```{r}
# saveRDS(cluster_ensembl, "/Users/niels/Documents/Uni/Stage/digital_twins/cluster_ensembl.rds")
# saveRDS(proteins_ensembl, "/Users/niels/Documents/Uni/Stage/digital_twins/proteins_ensembl.rds")
# saveRDS(neightbours_list, "/Users/niels/Documents/Uni/Stage/digital_twins/neightbours_list.rds")
# saveRDS(cluster_list, "/Users/niels/Documents/Uni/Stage/digital_twins/cluster_list.rds")
# saveRDS(betas_list, "/Users/niels/Documents/Uni/Stage/digital_twins/betas_list.rds")

# cluster_ensembl <- readRDS("/Users/niels/Documents/Uni/Stage/digital_twins/cluster_ensembl.rds")
# proteins_ensembl <- readRDS("/Users/niels/Documents/Uni/Stage/digital_twins/proteins_ensembl.rds")
# neightbours_list <- readRDS("/Users/niels/Documents/Uni/Stage/digital_twins/neightbours_list.rds")
# cluster_list <- readRDS("/Users/niels/Documents/Uni/Stage/digital_twins/cluster_list.rds")
# betas_list <- readRDS("/Users/niels/Documents/Uni/Stage/digital_twins/betas_list.rds")
```

#### Create biomarker to clust betas

```{r}
# Creating vector of all unique names inside the entries within betas_list
biom_names <- unique(unlist(sapply(betas_list, names)))

# Creating a list of all unique values within the betas_list and corresponding betas
biom_betas <- lapply(seq_along(biom_names), function(ii) {
  biom_ii <- biom_names[ii]
  outp1 <- sapply(betas_list, function(betass) {
    if (biom_ii %in% names(betass)) {
      biom_betas_ii <- which(names(betass) %in% biom_ii)
      return_betas <- betass[biom_betas_ii]
      if (any(return_betas == 0)) return_betas[return_betas == 0] <- 1
      # if(any(biom_ii %in% return_betas)) return_betas[which(biom_ii %in% return_betas)] = 1
      return(return_betas)
      # names(return_betas) <- names(betass)[biom_betas_ii]
    } else {
      return(NULL)
    }
  })
  return(outp1)
})

# removing duplicates
biom_betas <- lapply(biom_betas, function(e) {
  outp <- unlist(e)
  names(outp) <- str_sub(names(outp), 1, 6)
  if (anyDuplicated(names(outp))) outp <- outp[-which(duplicated(names(outp)))]
  return(outp)
})

names(biom_betas) <- biom_names
```

#### Dataset simulation

```{r}
# Function to replace the mean of the means of the betas for each entry in biom_betas 
replace_with_means <- function(biom_betas, mean_values) {
  for (protein_name in names(biom_betas)) {
    cluster <- names(biom_betas[[protein_name]])
    mean_prots <- sapply(cluster, function(e) {
      mean_values[[e]]
    })
    mean_value <- mean(mean_prots)
    biom_betas[[protein_name]] <- mean_value
  }
  return(biom_betas)
}

# Function to replace the mean of the standard deviations of the betas for each entry in biom_betas 
replace_with_std <- function(biom_betas, mean_values) {
  for (protein_name in names(biom_betas)) {
    cluster <- names(biom_betas[[protein_name]])
    std_prots <- sapply(cluster, function(e) {
      std_values[[e]]
    })
    std_value <- mean(std_prots)
    biom_betas[[protein_name]] <- std_value
  }
  return(biom_betas)
}

# Setting the means of the biom_betas
mean_biom_betas <- replace_with_means(biom_betas, mean_values)
std_biom_betas <- replace_with_std(biom_betas, std_values)
```

#### Simulating sick individuals

```{r}
# Vector with all beta protein names
betas_proteins <- names(biom_betas) 

# Vector of proteins not in betas
rest_biom <- setdiff(names(biom_betas), data_proteins) 

# Variable to set how many sick individuals will be simulated
N_sick <- 50

# Simulating sick individuals with the added unique biom betas not in our original dataset
sick_sim <- sapply(seq_along(data_proteins), function(ii) {
  sig_protein <- data_proteins[ii]
  simulated_values <- rnorm(N_sick, mean = mean_values[[ii]], sd = std_values[[ii]])
  if (sig_protein %in% sig) {
    fold_change_index <- which(sig_protein == names(sig_fold))
    simulated_values <- simulated_values + sig_fold[[fold_change_index]]
    # print("fold")
  }
  return(simulated_values)
}) %>%
  cbind(
    .,
    sapply(rest_biom, function(e) {
      rnorm(N_sick, mean = mean_biom_betas[[e]] + sig_fold[[e]], sd = std_biom_betas[[e]])
    })
  )

# Naming the first 227 columns to match the gene names in our data and naming the rows
colnames(sick_sim)[1:227] <- colnames(data)
rownames(sick_sim) <- paste("sick", 1:N_sick, sep = "_")

# Simulating sick individuals values based on the betas in our 227 proteins
sick_sim_final <- sapply(seq_along(colnames(sick_sim)), function(ii) {
  sig_protein <- colnames(sick_sim)[ii]
  simulated_values <- sick_sim[, sig_protein]
  if (sig_protein %in% names(betas_list)) {
    entry <- betas_list[[which(names(betas_list) %in% sig_protein)]]
    selected_proteins <- names(entry)
    # if ((sig_protein %in% selected_proteins)) cat("biomarker =", sig_protein, "\n")
    if (!(sig_protein %in% selected_proteins)) {
      subset_dataframe <- as.matrix(sick_sim[, selected_proteins])
      num_vector <- unname(entry)
      simulated_values <- subset_dataframe %*% num_vector
      # print("Biomarker")
    }
  }
  return(simulated_values)
})

# Naming the columns of sick_sim_final
colnames(sick_sim_final) <- colnames(sick_sim)
```


```{r}
# Variable to set how many healthy individuals will be simulated
N_healthy <- 50

# Simulating healthy individuals with the added unique biom betas not in our original dataset
healthy_sim <- sapply(seq_along(data_proteins), function(ii) {
  sig_protein <- data_proteins[ii]
  simulated_values <- rnorm(N_healthy, mean = mean_values[[ii]], sd = std_values[[ii]])
  if (sig_protein %in% sig) {
    fold_change_index <- which(sig_protein == names(sig_fold))
    simulated_values <- simulated_values #+ 0*sig_fold[[fold_change_index]]
  }
  return(simulated_values)
}) %>%
  cbind(sapply(rest_biom, function(e){
  rnorm(N_healthy, mean = mean_biom_betas[[e]] + 0*sig_fold[[e]], sd = std_biom_betas[[e]])
})
)

colnames(healthy_sim)[1:227] <- colnames(data)
rownames(healthy_sim) <- paste("healthy", 1:N_healthy, sep = "_")

# Simulating healthy individuals values based on the betas in our 227 proteins
healthy_sim_final <- sapply(seq_along(colnames(healthy_sim)), function(ii) {
  sig_protein <- colnames(healthy_sim)[ii]
  simulated_values <- healthy_sim[, sig_protein]
  if (sig_protein %in% names(betas_list)) {
    entry <- betas_list[[which(names(betas_list) %in% sig_protein)]]
    selected_proteins <- names(entry)
    if((sig_protein %in% selected_proteins)) cat("biomarker =", sig_protein, "\n")
    if(!(sig_protein %in% selected_proteins)) {
      subset_dataframe <- as.matrix(healthy_sim[, selected_proteins])
      num_vector <- unname(entry)
      simulated_values <- subset_dataframe %*% num_vector
      # print("Biomarker")
    }
  }
  return(simulated_values)
})

# Naming the columns of healthy healthy_sim_final
colnames(healthy_sim_final) <- colnames(healthy_sim)

# Creating a dataframe of sick and healthy individuals which only contains the genes from our original dataset
DT_dat <- rbind(healthy_sim_final[,data_proteins], sick_sim_final[,data_proteins])
```

```{r}
STRING_data_sim <- function(N_healthy, N_sick) {
  # Vector with all beta protein names
  betas_proteins <- names(biom_betas) 
  
  # Vector of proteins not in betas
  rest_biom <- setdiff(names(biom_betas), data_proteins) 
  
  # Simulating sick individuals with the added unique biom betas not in our original dataset
  sick_sim <- sapply(seq_along(data_proteins), function(ii) {
    sig_protein <- data_proteins[ii]
    simulated_values <- rnorm(N_sick, mean = mean_values[[ii]], sd = std_values[[ii]])
    if (sig_protein %in% sig) {
      fold_change_index <- which(sig_protein == names(sig_fold))
      simulated_values <- simulated_values + sig_fold[[fold_change_index]]
      # print("fold")
    }
    return(simulated_values)
  }) %>%
    cbind(
      .,
      sapply(rest_biom, function(e) {
        rnorm(N_sick, mean = mean_biom_betas[[e]] + sig_fold[[e]], sd = std_biom_betas[[e]])
      })
    )
  
  # Naming the first 227 columns to match the gene names in our data and naming the rows
  colnames(sick_sim)[1:227] <- colnames(data)
  rownames(sick_sim) <- paste("sick", 1:N_sick, sep = "_")
  
  # Simulating sick individuals values based on the betas in our 227 proteins
  sick_sim_final <- sapply(seq_along(colnames(sick_sim)), function(ii) {
    sig_protein <- colnames(sick_sim)[ii]
    simulated_values <- sick_sim[, sig_protein]
    if (sig_protein %in% names(betas_list)) {
      entry <- betas_list[[which(names(betas_list) %in% sig_protein)]]
      selected_proteins <- names(entry)
      # if ((sig_protein %in% selected_proteins)) cat("biomarker =", sig_protein, "\n")
      if (!(sig_protein %in% selected_proteins)) {
        subset_dataframe <- as.matrix(sick_sim[, selected_proteins])
        num_vector <- unname(entry)
        simulated_values <- subset_dataframe %*% num_vector
        # print("Biomarker")
      }
    }
    return(simulated_values)
  })
  
  # Naming the columns of sick_sim_final
  colnames(sick_sim_final) <- colnames(sick_sim)
  
  # Simulating healthy individuals with the added unique biom betas not in our original dataset
  healthy_sim <- sapply(seq_along(data_proteins), function(ii) {
    sig_protein <- data_proteins[ii]
    simulated_values <- rnorm(N_healthy, mean = mean_values[[ii]], sd = std_values[[ii]])
    if (sig_protein %in% sig) {
      fold_change_index <- which(sig_protein == names(sig_fold))
      simulated_values <- simulated_values #+ 0*sig_fold[[fold_change_index]]
    }
    return(simulated_values)
  }) %>%
    cbind(sapply(rest_biom, function(e){
      rnorm(N_healthy, mean = mean_biom_betas[[e]] + 0*sig_fold[[e]], sd = std_biom_betas[[e]])
    })
    )
  
  colnames(healthy_sim)[1:227] <- colnames(data)
  rownames(healthy_sim) <- paste("healthy", 1:N_healthy, sep = "_")
  
  # Simulating healthy individuals values based on the betas in our 227 proteins
  healthy_sim_final <- sapply(seq_along(colnames(healthy_sim)), function(ii) {
    sig_protein <- colnames(healthy_sim)[ii]
    simulated_values <- healthy_sim[, sig_protein]
    if (sig_protein %in% names(betas_list)) {
      entry <- betas_list[[which(names(betas_list) %in% sig_protein)]]
      selected_proteins <- names(entry)
      # if((sig_protein %in% selected_proteins)) cat("biomarker =", sig_protein, "\n")
      if(!(sig_protein %in% selected_proteins)) {
        subset_dataframe <- as.matrix(healthy_sim[, selected_proteins])
        num_vector <- unname(entry)
        simulated_values <- subset_dataframe %*% num_vector
        # print("Biomarker")
      }
    }
    return(simulated_values)
  })
  
  # Naming the columns of healthy healthy_sim_final
  colnames(healthy_sim_final) <- colnames(healthy_sim)
  
  # Creating a dataframe of sick and healthy individuals which only contains the genes from our original dataset
  DT_dat <- rbind(healthy_sim_final[,data_proteins], sick_sim_final[,data_proteins])
  
  # Return the resulting data frame
  return(DT_dat)
}

# Usage example:
result <- STRING_data_sim(N_healthy = 50, N_sick = 50)
 
```


```{r}
tibble(as.data.frame(DT_dat[,unique(unlist(sapply(biom_betas, names)))])) %>% bind_cols(group = rep(c("healthy","sick"),times=c(N_healthy, N_sick)), .) %>% pivot_longer(cols = -group) %>% ggplot(aes(x=name, y=value, col=group)) + geom_boxplot()
```
#### O2M fit

```{r}
# Reading in the previous fit
fit_o2m <- readRDS("/Users/niels/Documents/Uni/Stage/digital_twins/fit_o2m")

# Creating scores based on previous fit
tot_scores <- scale(DT_dat %*% fit_o2m$W.)

# Reading in previous cluster details
cluster_details <- readRDS("/Users/niels/Documents/Uni/Stage/digital_twins/cluster_detailed.rds")
```

#### K-means clustering

```{r}
n_clusters <- 2
n_iterations <- 100

# function to cluster scores based on the lowest k-means
best_k_means <- function(data, n_iterations, n_clusters) {
  k_clusters_list <- lapply(1:n_iterations, function(i) {
    kmeans(data, centers = n_clusters, iter.max = i)
  })
  
  total_distances <- sapply(k_clusters_list, function(k_clusters) {
    sum(k_clusters$withinss)
  })
  
  selected_cluster <- k_clusters_list[[which.min(total_distances)]]
  best_cluster <- selected_cluster$cluster
  
  return(selected_cluster)
}

# Clustering based on scores
k_means_cluster <- best_k_means(tot_scores, n_iterations, n_clusters)
```

#### Scores

```{r}
fit_lda <- MASS::lda(tot_scores, k_means_cluster)

Prot_Betas <- OmicsPLS::loadings(fit_o2m,"Xj") %*% coef(fit_lda)
Prot_Betas_ord <- rownames(Prot_Betas)[order(Prot_Betas^2, decreasing = TRUE)]
Prot_Betas <- Prot_Betas[Prot_Betas_ord, ]

apply(DT_dat, 2, function(e) t.test(e ~ group)$p.val) %>% p.adjust("fdr")

# groups <- ifelse(grepl("healthy", rownames(DT_dat)), "healthy", "sick")
groups <- ifelse(grzepl(1, k_means_cluster), 1, 2)
  
p_values <- apply(DT_dat, 2, function(e) t.test(e ~ groups)$p.value)

adjusted_p_values <- p.adjust(p_values, "fdr")

adjusted_p_values[order(adjusted_p_values)]

clue::cl_predict(cluster_details, tot_scores)
conf_matrix <- caret::confusionMatrix(factor(clue::cl_predict(cluster_details, tot_scores)), factor(ifelse(1:100 <= 50, 2, 1)))

conf_matrix$byClass
```

```{r}
## repeat 200 times
num_simulations <- 200

# List of resulting cl_predict values
results_list <- list()

# Use lapply to run the simulation function num_simulations times
results_list <- lapply(1:num_simulations, function(i) {
  # Call the STRING_data_sim function with your desired N_healthy and N_sick values
  train_sim <- STRING_data_sim(N_healthy = 35, N_sick = 35)

  tot_scores <- scale(train_sim %*% fit_o2m$W.)

  cluster <-  best_k_means(tot_scores, n_iterations, n_clusters)

  test_sim <- STRING_data_sim(N_healthy = 500, N_sick = 500)
  test_tot_scores <- scale(test_sim %*% fit_o2m$W.)
  
  cluster_predict <- clue::cl_predict(cluster, test_tot_scores)
  
  conf_matrix <- caret::confusionMatrix(factor(cluster_predict), factor(ifelse(1:1000 <= 500, 2, 1)))
  
  result <- c(conf_matrix$byClass[1], conf_matrix$byClass[2])
  return(result)
})
# simulating training data 35:35

# Calculating components based on o2m

# New k-means clustering

# Simulating more test data 500:500

# cl_predict() using training k-means on test data

# Saving accuracy of prediction

```

